### ISSUE TITLE
Add Gradle Plugin docs page to JavaLite site

### ISSUE THREAD

**Issue by ipolevoy** [cschabl/activejdbc-gradle-plugin#3]
sources: https://github.com/javalite/javalite-site
Should be linked off of this page: http://javalite.io/documentation

**Comment by ipolevoy** [comment]
Please, include how to use, where to find sources, what version of plugin to use with what version of JavaLite (shall we synchronize version?), etc.

**Comment by cschabl** [comment]
@ipolevoy, the project uses semantic versioning. Major and minor version might change for its own reasons. The main concept of the plugin is that the version of ActiveJDBC instrumentation tool can be configured at runtime. It uses the API `org.javalite.instrumentation.Main.main(String[] args)`. As long as this API doesn't change, there is no need to release a new version of the plugin.  

The [JMeter Gradle plugin](https://github.com/jmeter-gradle-plugin/jmeter-gradle-plugin) adds a meta tag to its version that corresponds to the version of JMeter it uses. I'm not sure if this would be useful or confusing here, because the ActiveJDBC version isn't fixed.

**Comment by ipolevoy** [comment]
Got it, it thanks!
