### ISSUE TITLE
Release a new plugin for ActiveJDBC version version 2.3.1-j8

### ISSUE THREAD

**Issue by ipolevoy** [cschabl/activejdbc-gradle-plugin#7]

**Comment by cschabl** [comment]
Fixed with plugin version 1.5.

There's a new test "should use ActiveJDBC version 2.3.1-j8 ()" in [ActiveJDBCGradlePluginTest](https://github.com/cschabl/activejdbc-gradle-plugin/blob/master/src/test/groovy/de/schablinski/gradle/activejdbc/ActiveJDBCGradlePluginTest.groovy) testing the integration with ActiveJDBC 2.3.1-j8.
